project_id = "rxaygagrjikvfscetqhs"

[functions.cep-lookup]
verify_jwt = false

[functions.ibge-proxy]
verify_jwt = false

[functions.pix-create]
verify_jwt = false

[functions.pix-status]
verify_jwt = false

[functions.pix-webhook]
verify_jwt = false
